[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]

[tool.mypy]
strict = true
untyped_calls_exclude = "bladerf"

[[tool.mypy.overrides]]
module = "bladerf.*"
ignore_errors = true
