% Create a patchMicrostrip antenna backed with reflector
% Generated by MATLAB(R) 9.14 and Antenna Toolbox 5.4.
% Generated on: 06-Jun-2024 11:36:15

%% Antenna Properties 

antennaObject = design(reflector('Exciter', patchMicrostrip), 1575*1e6);
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1575*1e6;
% Define frequency range 
freqRange = (1417.5:15.75:1732.5)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
% figure;
% patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% figure;
% patternAzimuth(antennaObject, plotFrequency, 90, 'Azimuth', 0:5:360)
% elevation
% figure;
% patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

ar = axialRatio(antennaObject,plotFrequency,0,0);
