% Create a patchMicrostrip antenna
% Generated by MATLAB(R) 9.14 and Antenna Toolbox 5.4.
% Generated on: 28-Jun-2024 11:51:43

%% Antenna Properties 

% antennaObject = design(patchMicrostrip, 500*1e6);
% % Show
% figure;
% show(antennaObject) 
% 
% 
% d = dielectric("FR4");
% pm = patchMicrostrip(Substrate=d)
% 
% impedance(pm,linspace(1000e6,1600e6,10));
