% Create a helix antenna
% Generated by MATLAB(R) 9.14 and Antenna Toolbox 5.4.
% Generated on: 07-Jun-2024 11:36:32

%% Antenna Properties 

antennaObject = design(helix, 1574*1e6);
antennaObject.Load.Impedance = 50;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1574*1e6;
% Define frequency range 
freqRange = (1416.6:15.74:1731.4)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)


freq = linspace(1.3e9,1.9e9,101);
axialRatio(antennaObject,freq,0,0);
